<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

</body>

<script>
    /**
             * Promise 的含义 
            Promise 是异步编程的一种解决方案，比传统的解决方案——回调函数和事件——更合理和更强大。它由社区最早提出和实现，ES6 将其写进了语言标准，统一了用法，原生提供了Promise对象。

            所谓Promise，简单说就是一个容器，里面保存着某个未来才会结束的事件（通常是一个异步操作）的结果。从语法上说，Promise 是一个对象，从它可以获取异步操作的消息。Promise 提供统一的 API，各种异步操作都可以用同样的方法进行处理。

            Promise对象有以下两个特点。

            （1）对象的状态不受外界影响。Promise对象代表一个异步操作，有三种状态：pending（进行中）、fulfilled（已成功）和rejected（已失败）。只有异步操作的结果，可以决定当前是哪一种状态，任何其他操作都无法改变这个状态。这也是Promise这个名字的由来，它的英语意思就是“承诺”，表示其他手段无法改变。

            （2）一旦状态改变，就不会再变，任何时候都可以得到这个结果。Promise对象的状态改变，只有两种可能：从pending变为fulfilled和从pending变为rejected。只要这两种情况发生，状态就凝固了，不会再变了，会一直保持这个结果，这时就称为 resolved（已定型）。如果改变已经发生了，你再对Promise对象添加回调函数，也会立即得到这个结果。这与事件（Event）完全不同，事件的特点是，如果你错过了它，再去监听，是得不到结果的。

            注意，为了行文方便，本章后面的resolved统一只指fulfilled状态，不包含rejected状态。

            有了Promise对象，就可以将异步操作以同步操作的流程表达出来，避免了层层嵌套的回调函数。此外，Promise对象提供统一的接口，使得控制异步操作更加容易。

            Promise也有一些缺点。首先，无法取消Promise，一旦新建它就会立即执行，无法中途取消。其次，如果不设置回调函数，Promise内部抛出的错误，不会反应到外部。第三，当处于pending状态时，无法得知目前进展到哪一个阶段（刚刚开始还是即将完成）。

            如果某些事件不断地反复发生，一般来说，使用 Stream 模式是比部署Promise更好的选择。
             * 
             * 
            */

    //基本用法
    //ES6 规定，Promise对象是一个构造函数，用来生成Promise实例。

    //   const promise = new Promise(function(resolve, reject) {

    //   if (true /* 异步操作成功 */){
    //     resolve(value);
    //   } else {
    //     reject(error);
    //   }
    // });


    /**
     * Promise构造函数接受一个函数作为参数，该函数的两个参数分别是resolve和reject。它们是两个函数，
     * 由 JavaScript 引擎提供，不用自己部署。
        resolve函数的作用是，将Promise对象的状态从“未完成”变为“成功”（即从 pending 变为 resolved），
        在异步操作成功时调用，并将异步操作的结果，作为参数传递出去；

        reject函数的作用是，将Promise对象的状态从“未完成”变为“失败”（即从 pending 变为 rejected），
        在异步操作失败时调用，并将异步操作报出的错误，作为参数传递出去。

        Promise实例生成以后，可以用then方法分别指定resolved状态和rejected状态的回调函数。
     * 
     * 
     * 
    // */
    //     promise.then(function(value) {
    //     // success
    //     }, function(error) {
    //     // failure
    //     });

    /**
     * then方法可以接受两个回调函数作为参数。第一个回调函数是Promise对象的状态变为resolved时调用，
     * 第二个回调函数是Promise对象的状态变为rejected时调用。这两个函数都是可选的，不一定要提供。它们都接受Promise对象传出的值作为参数。
     * 下面是一个Promise对象的简单例子。
     */


    // function runSync(name){
    //     let p = new Promise(function(resolve,reject){
    //         resolve(name)
    //     })
    //     return p 
    // }
    // runSync("wang")


    //普通写法1
    // function person (){
    //     //这里的Promise中有两个参数,一个是 resolve下面是ok代替;一个是reject,error代替
    //     let p = new Promise(function( ok,error){
    //         setTimeout(() => {
    //             let num  = Math.ceil(Math.random()*10); //生成1-10的随机数
    //             if(num < 6){
    //                 ok(num) //如果进入到这里说明上面执行结果是正确的，这个时候把ok抛出给下面then中的第一个函数
    //             }else{
    //                 error(num+"数字太大了了")//如果进入到这里说明上面执行结果是错误的，这个时候把ok抛出给下面then中的第一个函数
    //             }

    //         }, 2000);
    //     })
    //     return p
    // }
    //  //then里面有两个参数，这里面的两个function 相当于两个蚕食，一个执行成功的，一个执行失败的
    // person().then(   
    //     function(data){    //这里是成功的函数
    //         console.log("不大")
    //         console.log(data)

    //     },
    //     function(reason){  //这里是失败的函数
    //         console.log("太大")
    //         console.log(reason)
    //     }

    // )

    //普通写法2，上面的可以写成这样

    function person() {
        //这里的Promise中有两个参数,一个是 resolve下面是ok代替;一个是reject,error代替
        let p = new Promise(function(ok, error) {
            setTimeout(() => {
                let num = Math.ceil(Math.random() * 10); //生成1-10的随机数
                if (num < 6) {
                    ok(num + "数字小于6") //如果进入到这里说明上面执行结果是正确的，这个时候把ok抛出给下面.then
                } else {
                    error(num + "数字大于6") //如果进入到这里说明上面执行结果是错误的，这个时候把error抛出给下面.catch
                }

            }, 2000);
        })
        return p
    }
    //.then代表的是返回的正确的回调;.then表示成功的回调
    person().then((data) => {
        console.log("不大")
        console.log("不大" + data) // 2数字小于6
    }).catch((data) => {
        console.log("太大")
        console.log("太大" + data) // 10数字大于6
    })

    //普通写法3，上面的可以写成这样

    let lower = new Promise((res, rej) => {
            setTimeout(() => {
                let num = Math.ceil(Math.random() * 10); //生成1-10的随机数
                if (num < 6) {
                    res(num + "数字小于6") //如果进入到这里说明上面执行结果是正确的，这个时候把ok抛出给下面then中的第一个函数
                } else {
                    rej(num + "数字大于6") //如果进入到这里说明上面执行结果是错误的，这个时候把ok抛出给下面then中的第一个函数
                }

            }, 2000);
        }).then((data) => {
            console.log(data) //4数字小于6
        }).catch((data) => {
            console.log(data) //8数字大于6

        })
        // console.log(lower)


    // let lowers= lower
    let lowers = new Promise((res, rej) => {
        setTimeout(() => {
            let num = Math.ceil(Math.random() * 10); //生成1-10的随机数
            if (num < 6) {
                res(num + "数字小于6") //如果进入到这里说明上面执行结果是正确的，这个时候把ok抛出给下面then中的第一个函数
            } else {
                rej(num + "数字大于6") //如果进入到这里说明上面执行结果是错误的，这个时候把ok抛出给下面then中的第一个函数
            }

        }, 2000);
    }).then((data) => {
        console.log("第一次接收成功") //第一次接收成功
        return data //这里return中将data抛出可以在下面的.then中接收
    }).then((data) => {
        console.log('第二次接收成功' + data) //第二次接收成功4数字小于6
    }).catch((data) => {
        console.log("第一次接收失败") //这里接收的还是抛出的错误的返回值
    })


    //以此类推只要在成功挥着失败中一直抛出，可以一直.then 或 .catch
    function person1(time) {
        console.log(time) //8
        this.time = time
            //这里的Promise中有两个参数,一个是 resolve下面是ok代替;一个是reject,error代替
        let p = new Promise(function(ok, error) {
            setTimeout(() => {
                console.log(this.time) //8
                if (this.time < 6) {
                    ok(this.time + "数字小于6") //如果进入到这里说明上面执行结果是正确的，这个时候把ok抛出给下面.then
                } else {
                    error(this.time + "数字大于6") //如果进入到这里说明上面执行结果是错误的，这个时候把error抛出给下面.catch
                }

            }, 2000);
        })
        return p
    }

    let time = Math.ceil(Math.random() * 10);
    person1(time).then((data) => {
            console.log("第一次接收成功" + data) //第一次接收成功4数字小于6
            return data
        }).then((data) => {
            console.log("第二次接收成功" + data) // 第二次接收成功4数字小于6
            return data
        }).then((data) => {
            console.log("第三次接收成功" + data) // 第三次接收成功4数字小于6
            return data
        }).then((data) => {
            console.log("第四次接收成功" + data) // 第四次接收成功4数字小于6
            return data
        }).then((data) => {
            console.log("第五次接收成功" + data) // 第五次接收成功4数字小于6

        }).catch((data) => {
            console.log("第一次接收失败" + data) // 第一次接收失败10数字大于6
            return data
        }).catch((data) => { //这里的第二次失败接收不了
            console.log("第二次接收失败" + data)
            return data
        })
        // .catch((data)=>{
        //     console.log("第三次接收失败"+data)  // 第四次接收成功4数字小于6
        //     return data
        // }).catch((data)=>{
        //     console.log("第四次接收失败"+data)  // 第四次接收成功4数字小于6
        //     return data
        // })
        // .catch((data)=>{
        //     console.log("第五次接收失败"+data)  // 第四次接收成功4数字小于6
        //     return data
        // })

    //现在来看.then可以一直接收，但是.catch不可以
    // Promise.all 接受一个数组中多个接口调用,返回一个数组里面包含返回的内容

   /**
     * @returns res :[
            {code: 0, msg: '操作成功', data: {…}, success: true},
            {code: 0, msg: '操作成功', data: {…}, success: true}
            ]
     * 4
     */
    
    Promise.all([one,two]).then( res =>{
        let [one,two] = res 
    })
</script>

</html>